version: '3.8'

services:
  thredds:
    container_name: thredds
    image: dxogo/mctw-cesam-thredds:latest
    ports:
      - "80:8080"
    volumes:
    # These bind mounts have to be changed inside the CESAM host
      - /var/thredds/public:/usr/local/tomcat/content/thredds/public  # The /public directory contains the .nc files
      - /var/thredds/web.xml:/usr/local/tomcat/webapps/thredds/WEB-INF/web.xml # The web.xml contains CORS configuration for the React server
      - /var/thredds/catalog.xml:/usr/local/tomcat/content/thredds/catalog.xml # The catalog.xml contains new catalog configuration for cesam data 
    networks:
      - thredds_network

  backend:
    container_name: backend
    image: dxogo/mctw-cesam-backend:latest
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    depends_on: 
      - thredds
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - thredds_network

  frontend:
    container_name: frontend
    image: dxogo/mctw-cesam-frontend:latest
    # build:
    #   context: ./frontend
    #   dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on: 
      - backend
    volumes:
      - ./frontend/src:/app/src
    networks:
      - thredds_network

networks:
  thredds_network:
