version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on: 
      - backend
    volumes:
      - ./frontend/src:/app/src
    networks:
      - thredds_network

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    depends_on: 
      - thredds
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - thredds_network

  thredds:
    container_name: thredds
    image: unidata/thredds-docker:5.5-SNAPSHOT
    ports:
      - "80:8080"
    volumes:
      - /var/thredds/public:/usr/local/tomcat/content/thredds/public  
      - /var/thredds/web.xml:/usr/local/tomcat/webapps/thredds/WEB-INF/web.xml
      - /var/thredds/catalog.xml:/usr/local/tomcat/content/thredds/catalog.xml
    networks:
      - thredds_network

networks:
  thredds_network:
