# Use a base image with Node.js for development
FROM node:alpine AS development

# Set environment variable
ENV NODE_ENV=development

RUN npm install -g nodemon

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies if not already installed
RUN npm config set registry https://registry.npmjs.org/
RUN npm i

# Copy the rest of the application code to the working directory
COPY . .

# Expose port 3001 for the Node.js backend
EXPOSE 3001

# Command to run your backend server (modify as needed)
CMD ["nodemon", "index.js"]
