export const SET_SELECTED_CITY = 'SET_SELECTED_CITY';
export const SET_EXPANDED = 'SET_EXPANDED';
export const TOGGLE_TOGGLE = 'TOGGLE_TOGGLE';
export const SET_ACTIVE_BUTTON = 'SET_ACTIVE_BUTTON';
export const FETCH_DAILY_DATA_SUCCESS = 'FETCH_DAILY_DATA_SUCCESS';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const UPDATE_DATE = 'UPDATE_DATE';